### ISSUE TITLE
'slope' may not be present in some reaches

### ISSUE THREAD

**Issue by nikki-t** [podaac/hydrocron#87]
It seems like there are cases where reach identifiers do not have slope associated with them.

This request:
```bash
curl --location --request GET 'https://soto.podaac.sit.earthdatacloud.nasa.gov/hydrocron/v1/timeseries?feature=Reach&feature_id=74222400191&output=csv&start_time=2023-07-28T00:00:00Z&end_time=2023-10-24T00:00:00Z&fields=reach_id,time_str,wse,width,slope'
```

Returns an internal server error and the Lambda logs show the following error:
```bash
[ERROR] KeyError: 'slope' Traceback (most recent call last):   File "/var/task/hydrocron/api/controllers/timeseries.py", line 280, in lambda_handler     results, hits = timeseries_get(feature, feature_id, start_time, end_time, output, fields)   File "/var/task/hydrocron/api/controllers/timeseries.py", line 50, in timeseries_get     data, hits = format_csv(feature.lower(), results, feature_id, fields)   File "/var/task/hydrocron/api/controllers/timeseries.py", line 162, in format_csv     csv += t[j]
[ERROR] KeyError: 'slope'
Traceback (most recent call last):
  File "/var/task/hydrocron/api/controllers/timeseries.py", line 280, in lambda_handler
    results, hits = timeseries_get(feature, feature_id, start_time, end_time, output, fields)
  File "/var/task/hydrocron/api/controllers/timeseries.py", line 50, in timeseries_get
    data, hits = format_csv(feature.lower(), results, feature_id, fields)
  File "/var/task/hydrocron/api/controllers/timeseries.py", line 162, in format_csv
    csv += t[j]
```

This seems to occur when `slope` is included in the fields parameters but is not present in the database query results.

**Comment by torimcd** [comment]
This error specifically for reachid=74222400191 was due to a node being incorrectly loaded as a reach (nodes have an associated reachid so it doesn't fail on load, we'll need to add a control there), but there is a broader issue where other reaches have a number of fields loaded empty instead of with the fillvalues that are present in the shapefile, which will cause the same behavior. Investigating further.

**Comment by torimcd** [comment]
Since changing to batch writes the granule fillvalues are being written correctly. Fixed by #92
